sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7
      env:
        - CS_CHECK=true
    - php: hhvm
  allow_failures:
    - php: hhvm

notifications:
  irc: "irc.freenode.org#apigility-dev"
  email: false

before_install:
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - ./vendor/bin/phpunit
  - if [[ $CS_CHECK == 'true' ]]; then ./vendor/bin/phpcs ; fi
